/**
 * The languages this server can speak, with a legacy provider code for each.
 *
 * Generated by scripts/build-languages.mjs from the word-level MT benchmark
 * (gemini-word-mt-bench) and afriso (https://github.com/AfriSpeech/afriso).
 * A language is here because Gemini scored medium tier (>=30% pass) or
 * better translating into it in that benchmark, with a short, specific
 * exclude list of colonial and diaspora languages that share the benchmark's
 * "spoken in an African country" criterion without being one -- see the
 * build script for the exact list and reasoning. Regenerate with
 * `npm run build:speech-data`.
 *
 * `google` is a Google Translate code where this project used to have one,
 * curated by hand, kept only for API backward compatibility. Where there
 * never was one, it is the language's own iso639_3 code, so the field stays
 * unique without claiming an association with a service nothing here calls.
 * Names and countries are only used for the catalogue and for deciding which
 * language a reader in a given country should default to; neither affects
 * what gets spoken.
 */
export const LANGUAGE_DATA = {
  abr: { name: "Abron", google: "abr", countries: ["CI","GH"] },
  ach: { name: "Acoli", google: "ach", countries: ["SS","UG"] },
  ada: { name: "Adangme", google: "ada", countries: ["GH"] },
  afr: { name: "Afrikaans", google: "af", countries: ["BW","MZ","NA","ZA","ZM","ZW"] },
  aka: { name: "Akan", google: "ak", countries: ["GH","TG"] },
  amh: { name: "Amharic", google: "am", countries: ["DJ","ET"] },
  bci: { name: "Baoulé", google: "bci", countries: ["CI"] },
  bin: { name: "Bini", google: "bin", countries: ["NG"] },
  bsq: { name: "Bassa", google: "bsq", countries: ["LR","SL"] },
  crs: { name: "Seselwa Creole French", google: "crs", countries: ["SC"] },
  dag: { name: "Dagbani", google: "dag", countries: ["GH","TG"] },
  dig: { name: "Digo", google: "dig", countries: ["KE","TZ"] },
  dik: { name: "Southwestern Dinka", google: "dik", countries: ["SD","SS"] },
  dip: { name: "Northeastern Dinka", google: "dip", countries: ["SD","SS"] },
  dyu: { name: "Dyula", google: "dyu", countries: ["BF","CI","ML"] },
  ebu: { name: "Embu", google: "ebu", countries: ["KE"] },
  efi: { name: "Efik", google: "efi", countries: ["CM","NG"] },
  ewe: { name: "Ewe", google: "ee", countries: ["GH","TG"] },
  fat: { name: "Fanti", google: "fat", countries: ["GH","TG"] },
  ffm: { name: "Maasina Fulfulde", google: "ffm", countries: ["BF","CI","GH","ML","MR","NE"] },
  fon: { name: "Fon", google: "fon", countries: ["BJ","TG"] },
  gaa: { name: "Ga", google: "gaa", countries: ["GH"] },
  gax: { name: "Borana-Arsi-Guji Oromo", google: "gax", countries: ["ET","KE","SO"] },
  gaz: { name: "West Central Oromo", google: "gaz", countries: ["ET","SD"] },
  gej: { name: "Gen", google: "gej", countries: ["BJ","TG"] },
  guw: { name: "Gun", google: "guw", countries: ["BJ","NG"] },
  ibo: { name: "Igbo", google: "ig", countries: ["NG"] },
  kbp: { name: "Kabiyè", google: "kbp", countries: ["BJ","GH","TG"] },
  kik: { name: "Kikuyu", google: "kik", countries: ["KE"] },
  kin: { name: "Kinyarwanda", google: "rw", countries: ["BI","CD","RW","TZ","UG"] },
  klu: { name: "Klao", google: "klu", countries: ["LR","SL"] },
  kqn: { name: "Kaonde", google: "kqn", countries: ["CD","ZM"] },
  kri: { name: "Krio", google: "kri", countries: ["GM","GN","SL","SN"] },
  kua: { name: "Kuanyama", google: "kua", countries: ["AO","NA"] },
  kus: { name: "Kusaal", google: "kus", countries: ["BF","GH","TG"] },
  lin: { name: "Lingala", google: "ln", countries: ["CD","CF","CG"] },
  loz: { name: "Lozi", google: "loz", countries: ["BW","NA","ZM","ZW"] },
  lua: { name: "Luba-Lulua", google: "lua", countries: ["AO","CD"] },
  lug: { name: "Ganda", google: "lug", countries: ["UG"] },
  mev: { name: "Mano", google: "mev", countries: ["CI","GN","LR"] },
  mfe: { name: "Morisyen", google: "mfe", countries: ["MU"] },
  nde: { name: "North Ndebele", google: "nde", countries: ["BW","ZM","ZW"] },
  ndo: { name: "Ndonga", google: "ndo", countries: ["AO","NA"] },
  nso: { name: "Pedi", google: "nso", countries: ["BW","ZA"] },
  nya: { name: "Chichewa", google: "ny", countries: ["MW","MZ","SZ","TZ","ZM","ZW"] },
  nyn: { name: "Nyankole", google: "nyn", countries: ["RW","TZ","UG"] },
  nyo: { name: "Nyoro", google: "nyo", countries: ["UG"] },
  nzi: { name: "Nzima", google: "nzi", countries: ["CI","GH"] },
  pcm: { name: "Nigerian Pidgin", google: "pcm", countries: ["NG"] },
  plt: { name: "Plateau Malagasy", google: "plt", countries: ["MG"] },
  pov: { name: "Upper Guinea Crioulo", google: "pov", countries: ["GM","GW","SN"] },
  run: { name: "Rundi", google: "run", countries: ["BI","CD","RW","TZ","UG"] },
  sag: { name: "Sango", google: "sg", countries: ["CD","CF","CG","TD"] },
  sna: { name: "Shona", google: "sn", countries: ["BW","ZA","ZM","ZW"] },
  som: { name: "Somali", google: "som", countries: ["DJ","ET","KE","SO"] },
  sot: { name: "Southern Sotho", google: "st", countries: ["LS","ZA"] },
  sus: { name: "Susu", google: "sus", countries: ["GN","GW","SL","SN"] },
  swc: { name: "Congo Swahili", google: "swc", countries: ["CD"] },
  swh: { name: "Swahili (individual language)", google: "sw", countries: ["BI","KE","MZ","RW","SO","TZ","UG"] },
  tir: { name: "Tigrinya", google: "ti", countries: ["DJ","ER","ET","SD"] },
  tiv: { name: "Tiv", google: "tiv", countries: ["CM","NG"] },
  tsn: { name: "Tswana", google: "tn", countries: ["BW","NA","ZA","ZM","ZW"] },
  tso: { name: "Tsonga", google: "ts", countries: ["MZ","SZ","ZA","ZW"] },
  tum: { name: "Tumbuka", google: "tum", countries: ["MW","ZM"] },
  twi: { name: "Twi", google: "ak", countries: ["GH","TG"] },
  urh: { name: "Urhobo", google: "urh", countries: ["NG"] },
  ven: { name: "Venda", google: "ven", countries: ["BW","ZA","ZW"] },
  wol: { name: "Wolof", google: "wo", countries: ["GM","GW","ML","MR","SN"] },
  xho: { name: "Xhosa", google: "xho", countries: ["BW","LS","ZA"] },
  yor: { name: "Yoruba", google: "yo", countries: ["BJ","NG"] },
};
