/**
 * The languages this server can speak, with the Google Translate provider code for each.
 *
 * Generated by scripts/build-languages.mjs from the African languages supported
 * in Google Translate, with country coverage and names from afriso (https://github.com/AfriSpeech/afriso).
 *
 * Translation pivots through Thai (`source -> th -> target`) before being universalised
 * via africa-g2p (https://github.com/AfriSpeech/africa-g2p) and spoken by Gemini Live.
 * Regenerate with `npm run build:speech-data`.
 */
export const LANGUAGE_DATA = {
  aar: { name: "Afar", google: "aa", countries: ["DJ","ER","ET"] },
  ach: { name: "Acoli", google: "ach", countries: ["SS","UG"] },
  afr: { name: "Afrikaans", google: "af", countries: ["BW","MZ","NA","ZA","ZM","ZW"] },
  aka: { name: "Akan", google: "ak", countries: ["GH","TG"] },
  alz: { name: "Alur", google: "alz", countries: ["CD","UG"] },
  amh: { name: "Amharic", google: "am", countries: ["DJ","ET"] },
  bam: { name: "Bambara", google: "bm", countries: ["CI","GN","ML","SN"] },
  bci: { name: "Baoulé", google: "bci", countries: ["CI"] },
  bem: { name: "Bemba (Zambia)", google: "bem", countries: ["BW","CD","MW","ZM"] },
  cgg: { name: "Chiga", google: "cgg", countries: ["CD","RW","UG"] },
  crs: { name: "Seselwa Creole French", google: "crs", countries: ["SC"] },
  din: { name: "Dinka", google: "din", countries: ["SD","SS"] },
  dov: { name: "Dombe", google: "dov", countries: ["ZW"] },
  dyu: { name: "Dyula", google: "dyu", countries: ["BF","CI","ML"] },
  ewe: { name: "Ewe", google: "ee", countries: ["GH","TG"] },
  fon: { name: "Fon", google: "fon", countries: ["BJ","TG"] },
  gaa: { name: "Ga", google: "gaa", countries: ["GH"] },
  hau: { name: "Hausa", google: "ha", countries: ["BF","BJ","CM","NE","NG","TD"] },
  ibo: { name: "Igbo", google: "ig", countries: ["NG"] },
  kin: { name: "Kinyarwanda", google: "rw", countries: ["BI","CD","RW","TZ","UG"] },
  knc: { name: "Central Kanuri", google: "kr", countries: ["CM","NE","NG","SD","TD"] },
  kri: { name: "Krio", google: "kri", countries: ["GM","GN","SL","SN"] },
  ktu: { name: "Kituba (Democratic Republic of Congo)", google: "ktu", countries: ["CD"] },
  lin: { name: "Lingala", google: "ln", countries: ["CD","CF","CG"] },
  lua: { name: "Luba-Lulua", google: "lua", countries: ["AO","CD"] },
  luo: { name: "Luo (Kenya and Tanzania)", google: "luo", countries: ["KE","TZ"] },
  mfe: { name: "Morisyen", google: "mfe", countries: ["MU"] },
  mlg: { name: "Malagasy", google: "mg", countries: ["MG"] },
  ndc: { name: "Ndau", google: "ndc-ZW", countries: ["MZ","ZW"] },
  nso: { name: "Pedi", google: "nso", countries: ["BW","ZA"] },
  nus: { name: "Nuer", google: "nus", countries: ["ET","SS"] },
  nya: { name: "Chichewa", google: "ny", countries: ["MW","MZ","SZ","TZ","ZM","ZW"] },
  orm: { name: "Oromo", google: "om", countries: ["ET","KE","SD","SO"] },
  run: { name: "Rundi", google: "rn", countries: ["BI","CD","RW","TZ","UG"] },
  sag: { name: "Sango", google: "sg", countries: ["CD","CF","CG","TD"] },
  sna: { name: "Shona", google: "sn", countries: ["BW","ZA","ZM","ZW"] },
  som: { name: "Somali", google: "so", countries: ["DJ","ET","KE","SO"] },
  sot: { name: "Southern Sotho", google: "st", countries: ["LS","ZA"] },
  ssw: { name: "Swati", google: "ss", countries: ["LS","MZ","SZ","ZA"] },
  sus: { name: "Susu", google: "sus", countries: ["GN","GW","SL","SN"] },
  swh: { name: "Swahili (individual language)", google: "sw", countries: ["BI","KE","MZ","RW","SO","TZ","UG"] },
  tir: { name: "Tigrinya", google: "ti", countries: ["DJ","ER","ET","SD"] },
  tiv: { name: "Tiv", google: "tiv", countries: ["CM","NG"] },
  tsn: { name: "Tswana", google: "tn", countries: ["BW","NA","ZA","ZM","ZW"] },
  tso: { name: "Tsonga", google: "ts", countries: ["MZ","SZ","ZA","ZW"] },
  tum: { name: "Tumbuka", google: "tum", countries: ["MW","ZM"] },
  twi: { name: "Twi", google: "ak", countries: ["GH","TG"] },
  ven: { name: "Venda", google: "ve", countries: ["BW","ZA","ZW"] },
  wol: { name: "Wolof", google: "wo", countries: ["GM","GW","ML","MR","SN"] },
  xho: { name: "Xhosa", google: "xh", countries: ["BW","LS","ZA"] },
  yor: { name: "Yoruba", google: "yo", countries: ["BJ","NG"] },
  zul: { name: "Zulu", google: "zu", countries: ["BW","LS","MZ","SZ","ZA"] },
};
